# typed: false
# frozen_string_literal: true

# Homebrew formula for the mosskeys CLI.
#
# The install / package name is `mosskeys-cli`; the command it installs is
# `mosskeys`. This formula installs the prebuilt, signed binary attached to the
# GitHub Release (not a from-source build), so it shares the exact artifact that
# ships with a CycloneDX SBOM, SHA-512 checksums, a keyless cosign signature, and
# SLSA build provenance. See RELEASING.md in moss-piglet/mosskeys-cli.
#
# This file is generated by .github/scripts/render-homebrew-formula.sh on each
# tagged release and committed to the tap repo (moss-piglet/homebrew-mosskeys-cli).
# Do not hand-edit checksums here.
class MosskeysCli < Formula
  desc "CLI and daemon for the mosskeys post-quantum key-transparency directory"
  homepage "https://mosskeys.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.3.0/mosskeys-0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "ddbcfbb5623c4277dfb01dc85133cc70cb55e764feb70fa083196f94461a6162"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.3.0/mosskeys-0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "8772ff01e33b2e788012bedf10bf212b7b998fc9e84fdd8f71c380efbea858dc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.3.0/mosskeys-0.3.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e948bc067b408f39f160a8cb026e7a19f2d024f866725f22b698ca9bd353cbf0"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.3.0/mosskeys-0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3f5c42d5210b236e7d458953879d9614d774c3de6a1f8cf5c03b3619c3fc6dd3"
    end
  end

  def install
    bin.install "mosskeys"
  end

  test do
    assert_match "mosskeys #{version}", shell_output("#{bin}/mosskeys --version")
  end
end
