# typed: false
# frozen_string_literal: true

# Homebrew formula for the mosskeys CLI.
#
# The install / package name is `mosskeys-cli`; the command it installs is
# `mosskeys`. This formula installs the prebuilt, signed binary attached to the
# GitHub Release (not a from-source build), so it shares the exact artifact that
# ships with a CycloneDX SBOM, SHA-512 checksums, a keyless cosign signature, and
# SLSA build provenance. See RELEASING.md in moss-piglet/mosskeys-cli.
#
# This file is generated by .github/scripts/render-homebrew-formula.sh on each
# tagged release and committed to the tap repo (moss-piglet/homebrew-mosskeys-cli).
# Do not hand-edit checksums here.
class MosskeysCli < Formula
  desc "CLI and daemon for the mosskeys post-quantum key-transparency directory"
  homepage "https://mosskeys.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.3.1/mosskeys-0.3.1-aarch64-apple-darwin.tar.gz"
      sha256 "e12ca63e47b205e90e557bf7c4e2d9041d3ed3931b7069a3a45b97fb8b75e1cd"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.3.1/mosskeys-0.3.1-x86_64-apple-darwin.tar.gz"
      sha256 "594cea83061b97b3ecad735808d115180fb4775918fe6e57e407408dfc7c7344"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.3.1/mosskeys-0.3.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0388ceffebc5474cfa2c5b5cb3013897405eebe1577a4fe12760d0a82ab77b96"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.3.1/mosskeys-0.3.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1c2df07c4c5b8f08e8ffae624f677404f65e29d5f1e17aa4f3d894601827feb8"
    end
  end

  def install
    bin.install "mosskeys"
    # Runs `mosskeys completions <shell>` at install time and links the
    # scripts into the brew-managed completion dirs (bash/zsh/fish).
    generate_completions_from_executable bin/"mosskeys", "completions"
  end

  test do
    assert_match "mosskeys #{version}", shell_output("#{bin}/mosskeys --version")
  end
end
