# typed: false
# frozen_string_literal: true

# Homebrew formula for the mosskeys CLI.
#
# The install / package name is `mosskeys-cli`; the command it installs is
# `mosskeys`. This formula installs the prebuilt, signed binary attached to the
# GitHub Release (not a from-source build), so it shares the exact artifact that
# ships with a CycloneDX SBOM, SHA-512 checksums, a keyless cosign signature, and
# SLSA build provenance. See RELEASING.md in moss-piglet/mosskeys-cli.
#
# This file is generated by .github/scripts/render-homebrew-formula.sh on each
# tagged release and committed to the tap repo (moss-piglet/homebrew-mosskeys-cli).
# Do not hand-edit checksums here.
class MosskeysCli < Formula
  desc "CLI and daemon for the mosskeys post-quantum key-transparency directory"
  homepage "https://mosskeys.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.2.5/mosskeys-0.2.5-aarch64-apple-darwin.tar.gz"
      sha256 "36deee2dd931e0ab29d99d89f303b1840835c6044ad589c8fe62be0d7cf2f2a1"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.2.5/mosskeys-0.2.5-x86_64-apple-darwin.tar.gz"
      sha256 "c85b0d764db4c24237af5dbaeef40fbd01696dd78b6d6b3af5ad819a9179a41b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.2.5/mosskeys-0.2.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2e1add9734f946275d2c9ffffa5be03d2b8eaad83d0fd1317bc74e86f1bec0c3"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.2.5/mosskeys-0.2.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a3a6915bddb353cfc038d1de9d642cd94377a27da8232425514f710f4c4b11ec"
    end
  end

  def install
    bin.install "mosskeys"
  end

  test do
    assert_match "mosskeys #{version}", shell_output("#{bin}/mosskeys --version")
  end
end
